clean::
	cd unzip60     && make clean && make tags
	cd zip30       && make clean && make tags
	cd minizip-aes && make clean && make tags

gcc::
	@echo Use set-mingw.bat
	cd zip30 && make -f win32/makefile.gcc
	cd unzip60 && make -f win32/makefile.gcc
